### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by JohannesTK** [yanghoonkim/NQG_ASs2s#2]
Great results with a great paper!

Will you be uploading your pre-trained weights?

Thanks!

**Comment by yanghoonkim** [comment]
Not exactly, There is a size limitation and the pre-trained weights can not be uploaded.

**Comment by JohannesTK** [comment]
I could provide you an AWS bucket where to host them.

**Comment by JohannesTK** [comment]
This is a public one.

https://s3.console.aws.amazon.com/s3/buckets/sidekik-public/ass2s

**Comment by yanghoonkim** [comment]
We don't have any plan to upload our pre-trained weights. Also, Our pre-trained weights are not compatible with the uploaded source code.
